development: &development
  adapter: postgresql
  database: kranti_web_development
  host: localhost
  port: 5432
  username: developer
  password: password
  encoding: utf8

test:
  <<: *development
  database: kranti_web_test

production:
  <<: *development
  database: kranti_web_production
